---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - spot.release.com
  resources:
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spot.release.com
  resources:
  - builds/finalizers
  verbs:
  - update
- apiGroups:
  - spot.release.com
  resources:
  - builds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spot.release.com
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - spot.release.com
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spot.release.com
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - spot.release.com
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spot.release.com
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spot.release.com
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - spot.release.com
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
