# permissions for end users to edit versioncontrols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: versioncontrol-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spot
    app.kubernetes.io/part-of: spot
    app.kubernetes.io/managed-by: kustomize
  name: versioncontrol-editor-role
rules:
- apiGroups:
  - spot.release.com
  resources:
  - versioncontrols
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spot.release.com
  resources:
  - versioncontrols/status
  verbs:
  - get
