apiVersion: spot.release.com/v1alpha1
kind: Build
metadata:
  labels:
    app.kubernetes.io/name: build
    app.kubernetes.io/instance: build-sample
    app.kubernetes.io/part-of: spot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spot
  name: build-sample
spec:
  # TODO(user): Add fields here
