apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/created-by: spot
  name: receiver
  namespace: spot-system
spec:
  selector:
    spot.release.com/pods: receiver
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/created-by: spot
  name: receiver
  namespace: spot-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: spot-workspace-issuer
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - receiver.tedtech.io
    secretName: receiver-cert
  rules:
  - host: "receiver.tedtech.io"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: "receiver"
            port:
              number: 3333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/created-by: spot
  name: receiver
  namespace: spot-system
spec:
  replicas: 1
  selector:
    matchLabels:
      spot.release.com/pods: receiver
  template:
    metadata:
      labels:
        spot.release.com/pods: receiver
    spec:
      serviceAccountName: spot-controller-manager
      containers:
        - image: public.ecr.aws/m7s6c4t5/receiver:latest
          name: receiver
          ports:
          - containerPort: 3333
