apiVersion: spot.release.com/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/instance: project-sample
    app.kubernetes.io/part-of: spot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spot
  name: click-mania
  namespace: spot-system
spec:
  template:
    host: "release.com"
    components:
      - name: "click-mania"
        command: 
          - "wait-for-it"
          - "mysql:3306"
          - "--"
          - "/srv/aurora-test"
          - "start"
        networks:
          - name: app #app.po.ngrok.app
            port: 3000
            ingress:
              path: "/" 
        environments:
          - name: "MYSQL_USER"
            as: "DB_USER"
          - name: "MYSQL_PASSWORD"
            as: "DB_PASSWORD"
          - name: "MYSQL_DATABASE"
            as: "DB_NAME"
          - name: "DB_HOST"
            value: "mysql"
        image:
          name: "pierolivierrh/click-mania"
          tag: "latest"
          registry:
            url: "pierolivierrh/click-mania"
          repository:
            dockerfile: Dockerfile
            context: "."
            url: github.com/releasehub-com/click-mania-test
            ref: "main"
            hash: "abc"
      - name: "mysql"
        networks:
          - name: "mysql"
            protocol: "tcp"
            port: 3306
        environments:
          - name: "MYSQL_USER"
          - name: "MYSQL_DATABASE"
          - name: "MYSQL_PASSWORD"
          - name: "MYSQL_ROOT_PASSWORD"
        image:
          name: "mysql"
          tag: "8.0.33"
    environments:
      - name: "MYSQL_USER"
        value: "big"
      - name: "MYSQL_DATABASE"
        value: "click-me"
      - name: "MYSQL_PASSWORD"
        value: "lebowski"
      - name: "MYSQL_ROOT_PASSWORD"
        value: "Yeah, well, that is just, like, your opinion, man."