apiVersion: spot.release.com/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/instance: workspace-sample
    app.kubernetes.io/part-of: spot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spot
  name: workspace-sample
  namespace: spot-system
spec:
  branch:
    name: "rel-1234-my-branch"
    url: "github.com/my-org/my-repo/my-branch"
  components:
    - name: "click-mania"
      services:
        - name: "https"
          port: 3000
          ingress: "app" #app.yolo.com
      image:
        name: "my-image" #u
        registry:
          type: "docker"
          url: "docker.io/my-org/my-image"
        repository_context:
          dockerfile: "Dockerfile"
          path: "." # Maybe this could be a git URL too? Relative path = branch.url
    - name: "mysql"
      services:
        - name: "tcp"
          port: 3036
      image:
        name: "mysql"
        tag: "8.0.33"
